### ISSUE TITLE
Consider swapping HTML minfier

### ISSUE THREAD

**Issue by sodevious** [djangocon/durham.djangocon.us#3]
npm warns of a high vulnerability with html-minifier: https://github.com/asyncLiz/minify-html-literals/issues/56

as the repo has not been updated in years (ie fix not likely), wondering if it's worth switching to something like https://github.com/posthtml/htmlnano
![Screen Shot 2024-05-01 at 2 09 16 PM](https://github.com/djangocon/durham.djangocon.us/assets/915966/0f4e65c8-d8a1-468e-a12d-05a12c6ce03a)

**Comment by mtrythall** [comment]
Good call. I'll swap this out.
